# Generated by Django 3.2.8 on 2021-10-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_commnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commnet',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
